apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: hp818ctc5-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/hp818ctc5-dotnet-basic-gitops